# Generated by Django 5.0.3 on 2024-03-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dish_manager", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishtype",
            options={
                "ordering": ["name"],
                "verbose_name": "DishType",
                "verbose_name_plural": "DishTypes",
            },
        ),
    ]
